### PR TITLE
Special functions

### PR DESCRIPTION
**Pull request by tmbb**
I've started work on adding support for more functions. The structure of the special functions is actually pretty simple and I could generate safe bindings for most of the functions in most of the files programmatically using a python script (which is currently not very well documented, unfortunayelly). I can even add the docs programmatically.

Some functions will have to be added manually, but what I've done saves a lot of time.

I think this could be merged once I've added tests and documentation to all the functions.

Also, my test infrastructure could be improved if I were better at writing rust, but I've just started learning it actually.

### CODE REVIEW

**Comment by PvdBerg1998** [comment]
Nice work! I can review if you let me know when it's ready to merge.

**Comment by tmbb** [comment]
I wonder if we shouldn't follow the GSL convention of having the `_e` special functions returning a `Result<ValWithError<f64>>` (useful for testing and for when you want to make sure the error is manageable, or even to do some interval arithmetic on errors) and have the "normal" special functions (i.e. those that don't end in `_e`) return raw floats, like is done in the C GLS library. This would break compatibility, of course.

While writing some sample code, I've found this new convention a bit better, I think.

What do you think?

**Comment by PvdBerg1998** [comment]
I don't intend to be 1:1 compatible, but I'm not sure what you mean. Do all functions return a `ValWithError` now, even if the GSL does not? Could you give an example?

**Comment by tmbb** [comment]
Maybe I wasn't clear, sorry. I think we whould have both:

```rust
pub fn bessel_Y0_e(x: f64) -> Result<ValWithError<f64>> {
    unsafe {
        let mut result = bindings::gsl_sf_result { val: 0.0, err: 0.0 };
        GSLError::from_raw(bindings::gsl_sf_bessel_Y0_e(x, &mut result))?;
        Ok(result.into())
    }
}
```

and 

```rust
pub fn bessel_Y0(x: f64) -> f64 {
    unsafe { bindings::gsl_sf_bessel_Y0(x) }
}
```

The first form is useful if you're doing error analysis on your calculations and the last form is useful when (if?) you don't care about that.

**Comment by PvdBerg1998** [comment]
Your proposed code sounds good to me. It's been a while since I wrote this crate, I might have decided I only needed the `_e` versions back then, but we can just do a major version bump.

**Comment by tmbb** [comment]
I've also added support for random number distributions, both the functions for the CDF and PDF and stuff like that and actual random number generation. Here I've departed a lot from the naming of the functions in the GSL library because I found their conventions a little confusing.

In my version, all functions that draw random numbers are named `draw_sample_from_*` (to draw a single sample) and `draw_samples_from_*` (to draw a whole `ndarray::Array` of samples; the array can be wither 1D or a 2D array, depending on the probability distribution). This does introduce a dependency on `ndarray`, but I belive that `ndarray` is currently the most sane way of handling arrays in rust.

Automatically generated docs here: https://tmbb.github.io/gsl_rust/gsl_rust/distribution/index.html

Ive mostly copied the code from [another wrapper](https://github.com/GuillaumeGomez/rust-GSL) of the GSL library to implement the random number functionalily. Despite the other wrapper being more complete, I actually prefer the architecture of your own wrapper (the other ones implements RNG distributions as traits of the Rng, which I don't like much). I also rather like the fact that your wrapper builds a static version of GSL from source instead of forcing the user to install it somehow.

Do these changes still respect your vision for the library?

**Comment by tmbb** [comment]
Also, I'm now using a self-contained Elixir project instead of that python script to generate the rust code from the templates. Elixir is easier to reason with, has better parsing libraries and pattern matching makes it much easier to do for what I need. The elixir code can be dropped from the final build, of course.

**Comment by PvdBerg1998** [comment]
I'm quite happy with your special functions, but the RNG seems like a different beast. Perhaps you could split this into a separate PR? I also would like to keep the dependencies and macro's minimal, but I think the `ndarray::Array` can be easily replaced by something else. We can discuss about this in the relevant PR.

I have no experience with Elixir. What is the Rust code generated from? A more common approach is make use of the output of `bindgen`, like I do in `build.rs`. Also, did you bundle the GSL website in order to generate the docs? I really like the LaTeX docs, but I would really like to keep the project easily maintainable and its complexity minimal.

**Comment by tmbb** [comment]
> I'm quite happy with your special functions, but the RNG seems like a different beast. Perhaps you could split this into a separate PR?

I agree, it should be split into a new PR. I just kept working on it and didn't thing of splitting it into a new branch. But I can do it, sure.

> Also, did you bundle the GSL website in order to generate the docs?

Yes, I did. I crawled over the index of the online manual and downloaded the pages that correspond to each section. Actually, the function signatures are taken from the manual HTML and not from the C code, because that's way easier to parse by my Elixir code.

> I really like the LaTeX docs, but I would really like to keep the project easily maintainable and its complexity minimal.

The LaTeX docs are generated by the browser using [KaTeX](https://katex.org/), there is no separate LaTeX compilation step. I include some HTML in the documentation header using the default cargo flags for that purpose which links to the KaTeX script from a CDN and runs it on the webpage. If you really want to go "javascriptless" you can use the rust bindings to the QuickJS engine and use that to run KaTeX (there are already packages for this), but that seems overly complicated, and it doesn't save you from linking to the CSS assets and fonts needed to display the math in the browser.

> What is the Rust code generated from?

The Rust code is generated from a number of templates inside the Elixir project. The generator is just some boilerplate to enapsulate the `gsl_*` functions in an `unsafe {...}` block. The way it works at the high level is the following:

1. The elixir code reads the function signatures from the HTML manual
2. It uses a custom parser of a subset of C to parse the some of the special function tests
3. It uses some heuristics to rename the functions according to the naming conventions I prefer and which I think are more appropriate to rust than the original C function names
4. It uses some template files (written in the `.eex` language) to actually generate the Rust code, the docs and the tests

So it's mostly string manipulation all the way down, with some clever parsing of C code.

There are some special cases in the Elixir code to reject functions that can't be written automatically (for example, functions that take or return vectors).

For the docs, the Elixir code converts the HTML into markdown and it does something clever which is to get the LaTeX text from the `alt` attribute of the `` tag (the GSL manual uses latex to convert the equations into images instead of KaTeX like I do). After doing all of this, it rearranges the newlines in markdown according to heuristics to make sure the first sentence is separated from the rest in order to have paragraphs that play better with the way rust wants the documentation to be.

**Comment by PvdBerg1998** [comment]
> I agree, it should be split into a new PR. I just kept working on it and didn't thing of splitting it into a new branch. But I can do it, sure.

Thanks! The PR is becoming a bit too large for me to review :sweat_smile: 
I think implementing the Rand API makes the most sense, even if it's quite complicated (iirc). However, it's good to compare the GSL API to the Rand ecosystem, are there many algorithms which have not been implemented in native Rust yet?

That said, it seems you took quite a lot of code from the other wrapper, and in my experience this other crate is not completely safe / UB free. (That's actually one of the reasons I wrote this crate a while ago!) Maybe we can reduce the amount of coverage in this part, and manually implement just the bits that are missing in the ecosystem.

> Yes, I did. I crawled over the index of the online manual and downloaded the pages that correspond to each section. Actually, the function signatures are taken from the manual HTML and not from the C code, because that's way easier to parse by my Elixir code.

My main concern is that I would like to avoid bundling a crawled copy of the GSL website. Do you think it's feasible to instead refer to the source of the docs (https://github.com/ampl/gsl/tree/55c260c1eb103e960998a290d84558ae7d8062c4/doc)? This is not in HTML format but it might be similar enough. GSL is referenced in the repository already anyway. This would make sure the information is never out of date. I think generating the bindings for the special functions makes sense, as it's mostly just calling the c function directly.

> The LaTeX docs are generated by the browser using [KaTeX](https://katex.org/), there is no separate LaTeX compilation step. I include some HTML in the documentation header using the default cargo flags for that purpose which links to the KaTeX script from a CDN and runs it on the webpage. If you really want to go "javascriptless" you can use the rust bindings to the QuickJS engine and use that to run KaTeX (there are already packages for this), but that seems overly complicated, and it doesn't save you from linking to the CSS assets and fonts needed to display the math in the browser.

No, that makes sense.

Thanks for the effort!

**Comment by tmbb** [comment]
> think implementing the Rand API makes the most sense, even if it's quite complicated (iirc)

Ok, I've been reading it and it doesn't seem that complex. But maybe I didn't go deep enough.

> My main concern is that I would like to avoid bundling a crawled copy of the GSL website.

You don't need to bundle it, the docs have already been included in the rust files. The HTML is just a convenient way of getting the docs. You could just delete the Elixir code and the whole HTML right now and the docs would still be in the rust files.

> Do you think it's feasible to instead refer to the source of the docs (https://github.com/ampl/gsl/tree/55c260c1eb103e960998a290d84558ae7d8062c4/doc)? 

No, that would require parsing RST, which is orders of magnitude harder than parsing HTML, unfortunately. But as I said above, you can just remove all elixir code right now and keep the rust code.

**Pull request closed without merging**
